create table current_equity (
  id integer primary key generated by default as identity,
  userid integer references FSE_users(id),
  stock_symbol text not null,
  num_of_shares integer not null,
  groupid integer references FSE_group(id)
);