create table user_group (
  id integer primary key generated by default as identity,
  userid integer references FSE_users(id),
  groupid integer references FSE_group(id),
  cash_balance integer not null
);